// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/appstore/Ipad1.tsx": () => import("../components/mockups/appstore/Ipad1.tsx"),
  "./components/mockups/appstore/Ipad2.tsx": () => import("../components/mockups/appstore/Ipad2.tsx"),
  "./components/mockups/appstore/Iphone1.tsx": () => import("../components/mockups/appstore/Iphone1.tsx"),
  "./components/mockups/appstore/Iphone2.tsx": () => import("../components/mockups/appstore/Iphone2.tsx"),
  "./components/mockups/appstore/Iphone3.tsx": () => import("../components/mockups/appstore/Iphone3.tsx"),
  "./components/mockups/appstore/Iphone4.tsx": () => import("../components/mockups/appstore/Iphone4.tsx"),
  "./components/mockups/appstore/Iphone5.tsx": () => import("../components/mockups/appstore/Iphone5.tsx")
};
